[package]
name = "demystify-lua"
version = "0.1.0"
edition = "2024"
description = "Lua bindings for demystify, a constraint solving tool for explaining puzzles"
license = "MPL-2.0"
repository = "https://github.com/stacs-cp/demystify-rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
demystify = { path = "../demystify", version = "0.2.0" }
demystify-builder = { path = "../demystify-builder", version = "0.1.0" }
mlua = { version = "0.11", features = ["luajit", "module"] }
anyhow = "1.0"
